name: Release Bump on Develop

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # important pour git describe

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract bump type from last commit message
        id: version
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Last commit message: $COMMIT_MSG"

          if echo "$COMMIT_MSG" | grep -q "release:major"; then
            echo "bump=major" >> "$GITHUB_OUTPUT"
          elif echo "$COMMIT_MSG" | grep -q "release:minor"; then
            echo "bump=minor" >> "$GITHUB_OUTPUT"
          elif echo "$COMMIT_MSG" | grep -q "release:patch"; then
            echo "bump=patch" >> "$GITHUB_OUTPUT"
          else
            echo "bump=patch" >> "$GITHUB_OUTPUT"
            echo "No label found, default to patch"
          fi

      - name: Create release branch
        run: |
          VERSION=$(jq -r .version package.json)
          BRANCH="release/bump-$VERSION"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b $BRANCH

      - name: Bump version
        run: |
          npm version ${{ steps.version.outputs.bump }} --no-git-tag-version

      - name: Commit and push
        run: |
          git add package.json package-lock.json || true
          git commit -m "chore(release): bump version"
          git push origin $BRANCH

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Release ${{ steps.version.outputs.bump }}"
          body: "Auto PR: bump version after develop push."
          base: develop
          head: ${{ env.BRANCH }}
